# Generated by Django 5.1 on 2024-10-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
