# Generated by Django 5.1 on 2024-10-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='create',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='update',
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
