# Generated by Django 5.1 on 2024-09-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
