# Generated by Django 5.1 on 2024-09-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cui',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
