# Generated by Django 5.1 on 2024-10-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='confirmar_clave',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
