# Generated by Django 5.1 on 2024-09-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_egreso_productosegreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telefono',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cui',
            new_name='nitOCui',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nit',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correoElectronico',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, default='DEFAULT_CODE', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
