# Generated by Django 5.1 on 2024-09-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_rename_telefono_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nitOCui',
            new_name='nit_Cui',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, default='0', max_length=50, unique=True),
        ),
    ]
