# Generated by Django 5.1 on 2024-09-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_remove_cliente_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, default='0', max_length=50, unique=True),
        ),
    ]
